### ISSUE TITLE
Available options

### ISSUE THREAD

**Issue by antoninadert** [Joe-noh/svelte-validator#12]
First, thanks for this library this is really appreciated.
I wanted to know what is expected as the options configuration ? I don't really know how to use option and what a valid option object looks like (except { } ) 

Maybe you can update the readme with an example ? Current validators don't seem to use it right now

**Comment by Joe-noh** [comment]
@antoninadert 

Thank you for your feedback!

Currently the you can put **any** object as `option` (I believe the name is bad). For example, in readme and test, object with key `message` is given. But this library does not expect that the option have specific keys. Just put as value of validation results.

https://github.com/Joe-noh/svelte-validator/blob/c51b10797732f60a77b746e4dcb3578c7198b8f1/src/create-validator.js#L23-L28

Actually this is new born holiday project and there is huge room of improvement. If you have API ideas, issues or PRs are very welcome.
