### ISSUE TITLE
Additional default validators

### ISSUE THREAD

**Issue by antoninadert** [Joe-noh/svelte-validator#13]
Hello, as you asked for it, I believe some additional validators can be useful: 
- equal (value)
- notEqual (value)
- notBetweenLength (min, max)
- notBetweenValue (min, max)

Other improvements would be special comparators for dates :) 

I still need to try it and I may find more ideas for improvement

**Comment by Joe-noh** [comment]
Thanks for ideas!

I think it is more beautiful that provides `not()` helper so that we can use like `not(equal(3))`.

**Comment by Joe-noh** [comment]
Pushed as v0.2.0
